apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  replicas: 3
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: example
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    receiver: 'email'
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'scott@kaplans.com'
      from: 'scott@kaplans.com'
      smarthost: 'email-smtp.us-west-1.amazonaws.com:587'
      authUsername: 'AKIA3JKU5XUW2A5RGQMF'
      authPassword:
        name: aws-ses-secret
        key: password
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: prometheus-example-rules
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: PodAlert
      expr: count_values("up", up) < 2
