apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: docker.io/library/prometheus-example-app
          ports:
            - containerPort: 2112
