apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
        - name: back-end
          image: 775956577581.dkr.ecr.us-west-1.amazonaws.com/prometheus-example-app:latest
          ports:
            - name: prometheus
              containerPort: 2112
