apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  labels:
    app: prometheus-example-app
spec:
  selector:
    app: prometheus-example-app
  ports:
    - name: prometheus
      port: 2112
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-example-app
  labels:
    app: prometheus-example-app
spec:
  selector:
    matchLabels:
      app: prometheus-example-app
  endpoints:
  - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      app: prometheus-example-app
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    # Routing
    service.beta.kubernetes.io/aws-load-balancer-name: demo
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance

    # Access Control
    service.beta.kubernetes.io/load-balancer-source-ranges: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  type: LoadBalancer
  selector:
    prometheus: prometheus
  ports:
    - port: 9090
      targetPort: 9090
    
