- name: Install Docker
  hosts: localhost
  tasks:
    - name: Install packages
      yum:
        name:
        - docker
        state: latest

    - name: Start docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

